#+title: cuckoo-search.el

*cuckoo-search.el* adds content-based search to Elfeed.

** The Idea

[[https://github.com/skeeto/elfeed][Elfeed]] is a great and mature RSS reader for Emacs. Everyone using Emacs should give it a spin. However, for my particular (and probably niche) use-case it has one important short-coming: it does not allow to search the content of RSS feeds - only tags, titles, dates etc. 

*cuckoo-search* uses [[https://github.com/BurntSushi/ripgrep][ripgrep]]-magic to address this. It searches the content of all entries currently displayed for specific terms (regexp welcome). 

** Changelog

*0.1*
- Initial release

** Installation 

*** Use-package

This is my current setup:

#+begin_src elisp
(use-package cuckoo-search
  :straight (:host github :repo "rtrppl/cuckoo-search")
  :after (elfeed)
  :bind
  (:map elfeed-search-mode-map
	      ("C" . cuckoo-search)))
#+end_src

** Usage

*** cuckoo-search

When visiting the *elfeed-search* buffer invoke "C" (see above) or M-x cuckoo-search and enter a search term. As ripgrep is using /regexp/ and examines HTML files, you may want to add "\w" after words, for example "price\w" for "price".

Alternative you could also use "-w Taiwan|China|Ukraine" to search for either Taiwan, China or Ukraine as words.

** FAQ

A cuckoo draws on other birds to hatch his eggs. In a similar manner, this package uses some Elfeed-code and rg to create the search, hence the name.  
